bot:
  # client-token
  bot_token: ""
  # client-channel-id
  channel_id: -12345
  # количество товаров в одном сообщении
  per_page: 5

es:
  es_host: "localhost"
  es_port: 9200
  es_user: "username"
  es_pass: "password"
  es_connections_limit: 50
  connection_attempt: 13
  products: "index_name"
  traders: "index_name"
  consumers: "index_name"