version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:7.17.9
    container_name: elasticsearch
    restart: always
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
      - ./certs:/usr/share/elasticsearch/config/certs
      - /etc/localtime:/etc/localtime:ro
      - ./elasticsearch_plugins:/usr/share/elasticsearch/plugins

    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cat/health?h=status | grep -q green"]
      retries: 300
      interval: 1s

  kibana:
    image: kibana:7.17.9
    container_name: kibana
    restart: always
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_SECURITY_ENABLED=true
      - ELASTICSEARCH_USERNAME=${KIBANA_USERNAME}
      - ELASTICSEARCH_PASSWORD="${KIBANA_PASSWORD}"
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml

    depends_on:
      - elasticsearch

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601"]
      interval: 1s
      timeout: 5s
      retries: 120
